#!/bin/sh

# This is a script to create a MySQL DB from the .txt files
# in <http://www.w3.org/2008/04/DiabeticPatientsDataSet/> .
# $Id: createDB,v 1.1 2008/07/25 21:33:23 eric Exp $

CREDS='-u root -password=aca'

# convert to CSV by
if [ 1 -eq 1 ]; then
for f in *.txt; do s=`echo $f | sed 's/\.txt//1'` && perl -pe '
  # convert (oddly unquoted) dates to ISO8601 and quote them.
  s|(\d+)/(\d+)/(\d+) ([0-9:]+)|"\3-\1-\2T\4"|g;
  # normalize the boolean values
  s|"Y"|"1"|g;s|"N"|"0"|g;
  # remove leading and trailing spaces
  s|" +|"|g;s| +"|"|g;
  # use unix line delimiters
  s|\r\n|\n|;
' < $s.txt > $s.csv; done
fi

mysqladmin $CREDS -f drop coi;
mysqladmin $CREDS create coi;
mysql $CREDS coi < CreateDB.sql
